[tool.poetry]
name = "sample-env"
version = "0.1.0"
description = ""
authors = ["otamesi515"]
readme = "README.md"
packages = [{include = "sample_env"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
